<?php

/** @var $viewModel \Nbrabant\Offers\ViewModel\Category\Banners */
$viewModel = $block->getViewModel();

$banners = $viewModel->getBanners();

?>

<?php if (!empty($banners)): ?>

    <div class="slider-wrapper">
        <?php foreach ($banners as $banner): ?>
            <div class="slide">
                <a href="<?= $banner->getLink(); ?>">
                    <?= $banner->getLabel(); ?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>

<?php endif; ?>
